### ISSUE TITLE
Firefox got themed

### ISSUE THREAD

**Issue by WuerfelDev** [regolith-linux/regolith-gdm3-theme#1]
I really like the theme. I'm not sure but I think Firefox adapts the system theme in certain parts of its UI. The problem is that it looks weird with the theme. Personally I don't care because i don't use Firefox usually, but to make a good impression that should be kept in mind
![Screenshot from 2019-04-24 22-17-11](https://user-images.githubusercontent.com/12686819/56698387-4dc5e380-66e1-11e9-9c08-2af87898fd04.png)
As you can see its bad readable and the shadow is not applied directly on the frame

I'd prefer the theme to have a stronger contrast for better readability. Especially hints are bad

**Comment by kgilmer** [comment]
Thanks for reporting the issue.  I'll do some looking into the Arc theme that is used and see if there are specific fixes I can apply for Firefox.  When you mention your preference for stronger contrast, do you mean in Firefox or the Regolith overall?  Can you provide an example?

**Comment by WuerfelDev** [comment]
I find the font overall too dark. It is ok in a terminal but in other applications like gnome-settings its not readable enough for me (or its too "boring" because it looks like a slightly brighter version of the background)
I suggest using a default text color like here for the whole system
![SolarizedGit](https://user-images.githubusercontent.com/12686819/56722018-746a3580-6746-11e9-832c-0f8df05a80c6.png)
https://conemu.github.io/en/SolarizedColors.html

**Comment by kgilmer** [comment]
You can select another GTK theme with the GNOME tweak tool that's available in the Ubuntu software store.  Other GTK themes may be more to your liking :smile:
